name: PR Size Guard
description: Guard PR size and require test changes when needed.
author: JNewtons
branding:
  icon: shield
  color: blue
runs:
  using: node20
  main: dist/index.js
inputs:
  max_lines:
    description: Maximum total changed lines allowed in a PR
    required: false
    default: "400"
  max_files:
    description: Maximum changed files allowed in a PR
    required: false
    default: "25"
  test_paths:
    description: Comma separated list of folders considered tests (e.g. tests,__tests__)
    required: false
    default: "test,tests,__tests__"
  exclude:
    description: Comma separated glob patterns to ignore (e.g. **/package-lock.json,**/*.min.js)
    required: false
    default: ""
  mode:
    description: warn or fail
    required: false
    default: "warn"
  retries:
    description: Number of retries on transient API errors (HTTP 429/5xx)
    required: false
    default: "2"
permissions:
  pull-requests: write
  contents: read
